### ISSUE TITLE
can't find tinyTPU.h

### ISSUE THREAD

**Issue by jiuzhangzi** [jofrfu/tinyTPU#50]
Hello, I tried your project but could not find tinyTPU.h,Can you upload it?

**Comment by jofrfu** [comment]
This file is generated by Vivado as part of the board support package for your IP core. If you called your core differently than mine, you have to rename that. Nevertheless, the only case where this .h file is used was a test at an early stage of this project. You should use "sd_main.c" as your main file by defining "SD" globally.
